### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by kimjuno123** [kimjuno123/todo-app#1]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?

- [ ] 아래 파일을 포함합니다.
README.md
.gitignore
LICENSE

- [ ] GitHub Project Kanban
Todo App을 직접 만든다고 생각하고 이슈, 마일스톤을 스스로 정해봅니다.
GitHub Project Kanban을 만들고, 이슈와 마일스톤을 연결하고 칸반 뷰로 변경합니다

- [ ] Coz’ Git flow
직접 제작한 GitHub Repository에 main, dev 브랜치를 만듭니다.
dev 브랜치에서 main 브랜치로 Pull Request를 최소 1회 시도합니다.

### 예상 작업 시간
ex) 3h
